// packages/vike-themes/react/ThemeProvider.jsx
// The React binding (vike-themes/react subpath) over the framework-agnostic
// vike-themes core. It owns the two runtime axes: the active THEME (brand) and the
// APPEARANCE (mode: system/light/dark). The core turns a (theme, appearance) pair
// into CSS (themeToAppearanceCss); this applies it and persists each axis to a cookie.
//
// SSR-safe: the provider renders from `theme`/`appearance` props (a page reads the
// cookies off pageContext and passes them in), so first paint matches and there is
// no flash. `system` is applied via the core's `@media (prefers-color-scheme)` CSS,
// so it follows the OS even before hydration.
import { useState, useMemo, useCallback, useEffect } from 'react'
import { themeToAppearanceCss, baseCss, presets, APPEARANCES } from '../runtime.js'
import { ThemeCtx } from './context.js'

const writeCookie = (name, value) => {
  if (typeof document === 'undefined') return
  document.cookie = `${name}=${value}; Path=/; Max-Age=31536000; SameSite=Lax`
}

export function ThemeProvider({ themes = presets, theme: initialTheme = 'default', appearance: initialAppearance = 'system', children }) {
  const names = Object.keys(themes)
  const [themeName, setThemeName] = useState(themes[initialTheme] ? initialTheme : names[0])
  const [appearance, setApp] = useState(APPEARANCES.includes(initialAppearance) ? initialAppearance : 'system')
  const theme = themes[themeName]

  // Props are re-derived per page (cookie or a page-level config override), so a
  // client-side nav can hand us a new theme/appearance; sync it. A user selection
  // still wins because it is written to the cookie and comes back as the next prop.
  useEffect(() => {
    if (themes[initialTheme]) setThemeName(initialTheme)
  }, [initialTheme, themes])
  useEffect(() => {
    if (APPEARANCES.includes(initialAppearance)) setApp(initialAppearance)
  }, [initialAppearance])

  const setTheme = useCallback(
    (next) => {
      if (!themes[next]) return
      setThemeName(next)
      writeCookie('vike_theme', next)
    },
    [themes],
  )

  const setAppearance = useCallback((next) => {
    if (!APPEARANCES.includes(next)) return
    setApp(next)
    writeCookie('vike_appearance', next)
  }, [])

  const value = useMemo(
    () => ({ theme, themeName, themes, names, setTheme, appearance, appearances: APPEARANCES, setAppearance }),
    [theme, themeName, themes, names, setTheme, appearance, setAppearance],
  )

  return (
    <ThemeCtx.Provider value={value}>
      {/* The whole theme contract: the active brand's variables for the active
          appearance (system -> light + a prefers-color-scheme dark media rule),
          plus the minimal base/reset authored against those variables. */}
      <style
        data-vike-theme={themeName}
        data-vike-appearance={appearance}
        dangerouslySetInnerHTML={{ __html: `${themeToAppearanceCss(theme, appearance, ':root')}\n${baseCss}` }}
      />
      {children}
    </ThemeCtx.Provider>
  )
}

// packages/vike-themes/vue/ThemeProvider.vue
<script setup>
import { h, ref, computed, provide, watch } from 'vue'
import { themeToAppearanceCss, baseCss, presets, APPEARANCES } from '../runtime.js'
import { THEME_KEY } from './context.js'

const props = defineProps({
  themes: { type: Object, default: () => presets },
  theme: { type: String, default: 'default' },
  appearance: { type: String, default: 'system' },
})

const names = computed(() => Object.keys(props.themes))
const themeName = ref(props.themes[props.theme] ? props.theme : names.value[0])
const appearance = ref(APPEARANCES.includes(props.appearance) ? props.appearance : 'system')
const theme = computed(() => props.themes[themeName.value])

// Props are re-derived per page (cookie or a page-level config override), so a
// client-side nav can hand us a new theme/appearance; sync it. A user selection
// still wins because it is written to the cookie and comes back as the next prop.
watch(() => props.theme, (next) => { if (props.themes[next]) themeName.value = next })
watch(() => props.appearance, (next) => { if (APPEARANCES.includes(next)) appearance.value = next })

const css = computed(() =>
  `${themeToAppearanceCss(theme.value, appearance.value, ':root')}\n${baseCss}`
)

// The whole theme contract: the active brand's variables for the active appearance
// (system -> light + a prefers-color-scheme dark media rule), plus the minimal
// base/reset authored against those variables. Built with h() using `innerHTML`
// (Vue's SSR-safe equivalent of React's dangerouslySetInnerHTML) — `v-html` on a
// dynamic `<component :is="'style'">` does NOT serialize its content during SSR, so
// the <style> tag would render empty and the page would be unthemed on first paint.
const styleEl = computed(() =>
  h('style', {
    'data-vike-theme': themeName.value,
    'data-vike-appearance': appearance.value,
    innerHTML: css.value,
  }),
)

function writeCookie(name, value) {
  if (typeof document === 'undefined') return
  document.cookie = `${name}=${value}; Path=/; Max-Age=31536000; SameSite=Lax`
}

function setTheme(next) {
  if (!props.themes[next]) return
  themeName.value = next
  writeCookie('vike_theme', next)
}

function setAppearance(next) {
  if (!APPEARANCES.includes(next)) return
  appearance.value = next
  writeCookie('vike_appearance', next)
}

provide(THEME_KEY, {
  theme,
  themeName,
  themes: computed(() => props.themes),
  names,
  setTheme,
  appearance,
  appearances: APPEARANCES,
  setAppearance,
})
</script>
<template>
  <component :is="styleEl" />
  <slot />
</template>
