// packages/vike-admin/vue/DashboardPage.vue
<script setup>
import { useData } from 'vike-vue/useData'
const data = useData()
</script>
<template>
  <div :style="{ maxWidth: '760px', margin: '0 auto' }">
    <h1 :style="{ marginTop: 0, fontSize: '22px' }">Admin</h1>
    <p v-if="data.resources.length === 0" :style="{ color: 'var(--color-muted)' }">No resources have been contributed yet.</p>
    <div v-else :style="{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 'var(--space-md, 1rem)' }">
      <a
        v-for="r in data.resources"
        :key="r.table"
        :href="`/admin/${r.table}`"
        :style="{ display: 'block', border: '1px solid var(--color-border)', background: 'var(--color-surface)', borderRadius: 'var(--radius, 10px)', padding: 'var(--space-md, 1rem) var(--space-lg, 1.5rem)', textDecoration: 'none', color: 'var(--color-text)' }"
      >
        <div :style="{ fontSize: '16px', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px' }">
          <span v-if="r.icon" aria-hidden="true">{{ r.icon }}</span>
          <span>{{ r.label }}</span>
        </div>
        <div :style="{ color: 'var(--color-muted)', fontSize: '13px', marginTop: '4px' }"><code>{{ r.table }}</code></div>
      </a>
    </div>
  </div>
</template>

// packages/vike-admin/react/DashboardPage.jsx
// /admin — the dashboard. Renders one card per resource this install composed (the
// union of every extension's contributions), filtered server-side to what the signed-in
// user may view. Pure presentation: the data hook (vike-admin/data:dashboardData) did
// the resolving; this reads the view-model via useData().
import { useData } from 'vike-react/useData'

const card = {
  display: 'block',
  border: '1px solid var(--color-border)',
  background: 'var(--color-surface)',
  borderRadius: 'var(--radius, 10px)',
  padding: 'var(--space-md, 1rem) var(--space-lg, 1.5rem)',
  textDecoration: 'none',
  color: 'var(--color-text)',
}

export default function DashboardPage() {
  const { resources } = useData()
  return (
    <div style={{ maxWidth: 760, margin: '0 auto' }}>
      <h1 style={{ marginTop: 0, fontSize: 22 }}>Admin</h1>
      {resources.length === 0 ? (
        <p style={{ color: 'var(--color-muted)' }}>No resources have been contributed yet.</p>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 'var(--space-md, 1rem)' }}>
          {resources.map((r) => (
            <a key={r.table} href={`/admin/${r.table}`} style={card}>
              <div style={{ fontSize: 16, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 8 }}>
                {r.icon ? <span aria-hidden="true">{r.icon}</span> : null}
                <span>{r.label}</span>
              </div>
              <div style={{ color: 'var(--color-muted)', fontSize: 13, marginTop: 4 }}>
                <code>{r.table}</code>
              </div>
            </a>
          ))}
        </div>
      )}
    </div>
  )
}
