// packages/vike-admin/vue/NewPage.vue
<script setup>
import { useData } from 'vike-vue/useData'
import { FormFields } from './FormFields.js'
import { singular } from '../text.js'

const data = useData()

</script>
<template>
  <div v-if="!data.apiWrite" :style="{ maxWidth: '520px', margin: '0 auto' }">
    <div :style="{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }">
      <h1 :style="{ margin: 0, fontSize: '22px' }">New {{ singular(data.label) }}</h1>
      <a :href="`/admin/${data.table}`" :style="{ color: 'var(--color-muted)', fontSize: '14px' }">← {{ data.label }}</a>
    </div>
    <form method="post" :action="`/admin/${data.table}/new`" :style="{ marginTop: 'var(--space-md, 1rem)', border: '1px solid var(--color-border)', background: 'var(--color-surface)', borderRadius: 'var(--radius, 10px)', padding: 'var(--space-lg, 1.5rem)', display: 'grid', gap: 'var(--space-md, 1rem)' }">
      <FormFields :fields="data.fields" />
      <div>
        <button type="submit" :style="{ background: 'var(--color-primary)', color: 'var(--color-primary-text, #fff)', border: 'none', padding: '0.55rem 1.1rem', borderRadius: 'var(--radius, 8px)', fontSize: '14px', cursor: 'pointer' }">Create</button>
      </div>
    </form>
  </div>
</template>

// packages/vike-admin/react/NewPage.jsx
// /admin/:table/new — the create form. An input per resolved field (FormFields derives
// the control from each field's type, including FK selects). It POSTs to its OWN route;
// the data hook (vike-admin/data:newData) owns the POST: it inserts through universal-orm
// and redirects back to the list. No client JS, no fetch — a plain form post, SSR all the
// way.
import { useData } from 'vike-react/useData'
import { FormFields } from './FormFields.jsx'
import { singular } from '../text.js'

export default function NewPage() {
  const data = useData()
  // The agent API (#115) renders this route to run newData's create, then reads the JSON
  // result off pageContext — the HTML is never used. Render nothing rather than crash on the
  // missing form fields.
  if (data.apiWrite) return null
  const { table, label: title, fields } = data
  return (
    <div style={{ maxWidth: 520, margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h1 style={{ margin: 0, fontSize: 22 }}>New {singular(title)}</h1>
        <a href={`/admin/${table}`} style={{ color: 'var(--color-muted)', fontSize: 14 }}>
          &larr; {title}
        </a>
      </div>

      <form
        method="post"
        action={`/admin/${table}/new`}
        style={{
          marginTop: 'var(--space-md, 1rem)',
          border: '1px solid var(--color-border)',
          background: 'var(--color-surface)',
          borderRadius: 'var(--radius, 10px)',
          padding: 'var(--space-lg, 1.5rem)',
          display: 'grid',
          gap: 'var(--space-md, 1rem)',
        }}
      >
        <FormFields fields={fields} />
        <div>
          <button
            type="submit"
            style={{
              background: 'var(--color-primary)',
              color: 'var(--color-primary-text, #fff)',
              border: 'none',
              padding: '0.55rem 1.1rem',
              borderRadius: 'var(--radius, 8px)',
              fontSize: 14,
              cursor: 'pointer',
            }}
          >
            Create
          </button>
        </div>
      </form>
    </div>
  )
}

// "Users" -> "User" for the heading; harmless if a label isn't a plain plural.
